name: helm-upgrade
run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: 'Environment to deploy'
        type: string
      version:
        required: true
        type: string
      helm-values-path:
        type: string
        default: './helm-charts/todoapp/values.yaml'
      helm-release-name:
        default: todoapp
        type: string
jobs:
  deploy-helm:
    name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Download Helm Package
        uses: actions/download-artifact@v4
        with:
          name: helm-package
          path: .

      - name: Download Helm Artifacts
        uses: actions/download-artifact@v4
        with:
          name: helm-artifacts
          path: .

      - name: Setup Helm
        uses: azure/setup-helm@v4.2.0


      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AZURE_CLUSTER_NAME }}

      - name: Deploy Dry Helm
        run: |
          helm install --dry-run ${{ inputs.helm-release-name }} ./todoapp*.tgz -f ${{ inputs.helm-values-path }} \
            --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
            --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            --set todoapp.secrets.login="${{ secrets.TODOAPP_LOGIN }}" \
            --set todoapp.secrets.password="${{ secrets.TODOAPP_PASSWORD }}" \
            --set todoapp.secrets.DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
            --set todoapp.image.version=${{ github.sha }}

      - name: Deploy Helm
        run: |
          helm upgrade --install --atomic --wait --timeout 3600s --debug ${{ inputs.helm-release-name }} ./todoapp-*.tgz \
            -f ${{ inputs.helm-values-path }} \
            --set mysql.configs.MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" \
            --set mysql.configs.MYSQL_USER="${{ secrets.MYSQL_USER }}" \
            --set mysql.configs.MYSQL_PASSWORD="${{ secrets.MYSQL_PASSWORD }}" \
            --set todoapp.secrets.login="${{ secrets.TODOAPP_LOGIN }}" \
            --set todoapp.secrets.password="${{ secrets.TODOAPP_PASSWORD }}" \
            --set todoapp.secrets.DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
            --set todoapp.image.version=${{ github.sha }}
